import { notFound } from 'next/navigation';
import { Metadata } from 'next';
import { getPage } from '@/lib/contentful/api';
import { ComponentResolver } from '@/components/contentful/ComponentResolver';
import { Hero } from '@/components/features/Hero';
import { Footer } from '@/components/layout/Footer';

interface PageProps {
  params: Promise<{
    slug?: string[];
  }>;
}

// Helper to format slug
const formatSlug = (slugParams?: string[]) => {
  if (!slugParams || slugParams.length === 0) {
    return '/'; // Default to '/' slug for root path
  }
  return `/${slugParams.join('/')}`; // Ensure leading slash
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const pageSlug = formatSlug(slug);
  const page = await getPage(pageSlug);

  if (!page || !page.seo) {
    return {
      title: 'Contentful Next.js Campaign',
      description: 'Generated by create next app',
    };
  }

  const { seo } = page;

  return {
    title: seo.metaTitle,
    description: seo.metaDescription,
    robots: {
      index: seo.allowIndexing,
      follow: seo.allowIndexing,
    },
    openGraph: {
      title: seo.metaTitle,
      description: seo.metaDescription,
    },
  };
}

export default async function Page({ params }: PageProps) {
  const { slug } = await params;
  const pageSlug = formatSlug(slug);
  const page = await getPage(pageSlug);

  if (!page) {
    notFound();
  }

  return (
    <main className="min-h-screen flex flex-col relative bg-white">
      {page.hero && <Hero data={page.hero} />}

      <div className="flex-1 w-full">
        {page.mainContentCollection?.items.map((section) => (
          <ComponentResolver key={section.sys.id} component={section} />
        ))}
      </div>

      {page.footer && <Footer data={page.footer} />}
    </main>
  );
}
